{
 "title": "LINKS MPLS",
 "tags": [ "MPLS" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "ACSC - SPO/IP/44900 -  172.16.0.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "SCA__CENTRAL" },
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "SCA__CENTRAL" },
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DC - SP - BRE/IP/24955 - 172.29.254.254",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "DC - SP" },
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0.61"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "DC - SP" },
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0.61"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DC - SUL - BQE/IP/00305 - 172.29.255.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "DC - SUL" },
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0.8"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "DC - SUL" },
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0.8"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CSSJ - RJO/IP/23498 - 172.16.19.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "Router MPLS-CSSJ" },
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0.113"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "Router MPLS-CSSJ" },
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0.113"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "HST - PTS/IP/03540 - 172.16.28.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HST" },
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0.4"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HST" },
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0.4"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "HSJ - CCS/MULTI/60242 - 172.29.3.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HSJ" },
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HSJ" },
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "HCNSC - TRS/IP/00194 - 172.16.32.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HCNSC" },
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HCNSC" },
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CSC-PT - PTS/IP/03541 - 172.16.20.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "CCSCPT" },
     "item": {
      "filter": "Incoming traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "CCSCPT" },
     "item": {
      "filter": "Outgoing traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CSC-SP - SPO/IP/44901 - 172.16.15.1",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-SP" },
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-SP" },
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CSC-JF - JFA/IP/07758 - 172.16.36.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-JF" },
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-JF" },
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ESC - STA/IP/00156 - 172.16.4.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "ESC" },
     "item": {
      "filter": "Incoming traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "ESC" },
     "item": {
      "filter": "Outgoing traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "LMR - GRS/IP/03329 - 172.16.2.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "LMR" },
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/1.9"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HAM" },
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "HAM - SPO/IP/44897 - 172.29.4.1",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HAM" },
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HAM" },
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "HMRP - MULTI/60117 - 172.16.40.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HMRP" },
     "item": {
      "filter": "Incoming traffic on interface Multilink1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HMRP" },
     "item": {
      "filter": "Outgoing traffic on interface Multilink1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "HSL - - 172.16.12.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HSL" },
     "item": {
      "filter": "Incoming traffic on interface Multilink1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HSL" },
     "item": {
      "filter": "Outgoing traffic on interface Multilink1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CSC-GO - PLG/IP/00106 - 172.16.13.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-GO" },
     "item": {
      "filter": "Incoming traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-GO" },
     "item": {
      "filter": "Outgoing traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "HEC - VTA/IP/05268 - 172.29.2.1",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HEC" },
     "item": {
      "filter": "Incoming traffic on interface Multilink1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "HEC" },
     "item": {
      "filter": "Outgoing traffic on interface Multilink1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "AMB-ITA - ITE/IP/00177 - 172.16.11.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "AMB-ITA" },
     "item": {
      "filter": "Incoming traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "AMB-ITA" },
     "item": {
      "filter": "Outgoing traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CRI - SPO/IP/44895 - 172.16.3.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "CRI" },
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "CRI" },
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CSJI - RJO/IP/23498 - 172.16.41.250",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSJI" },
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/1.105"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSJI" },
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/1.105"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "HSI - BNU/IP/01070 - 10.14.0.1",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network Traffic" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HSI" },
     "item": { "filter": "Download LAN" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network Traffic" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HSI" },
     "item": { "filter": "Upload LAN" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "HNSC - TRO/IP/00308 - 10.13.0.254",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network Traffic" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HNSC" },
     "item": { "filter": "Download LAN" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network Traffic" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HNSC" },
     "item": { "filter": "Upload LAN" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "HSJ-T - TIJ/IP/00137 - 10.15.0.1",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network Traffic" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "IN" ],
       "text": "setAlias(IN)"
      }
     ],
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HSJ-TIJUCAS" },
     "item": { "filter": "Download port1" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network Traffic" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "OUT" ],
       "text": "setAlias(OUT)"
      }
     ],
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HSJ-TIJUCAS" },
     "item": { "filter": "Upload port1" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}