{
 "title": "MPLS IN/OUT SLA",
 "tags": [ "MPLS" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Disponibilidade",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Telefone Embratel: 0800 704 7521",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "BRE/IP/24955",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "DC - SP" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "DC - SP",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "DC - SP" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "DC - SP" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0.61"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "DC - SP" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0.61"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "BQE/IP/00305",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "DC - SUL" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "DC - SUL",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "DC - SUL" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "DC - SUL" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0.8"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "DC - SUL" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0.8"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ITE/IP/00177",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "AMB-ITA" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "AMB-ITA",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "AMB-ITA" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "AMB-ITA" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "AMB-ITA" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SPO/IP/44900",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "SCA__CENTRAL" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "ACSC",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "SCA__CENTRAL" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "SCA__CENTRAL" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "SCA__CENTRAL" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PLG/IP/00106",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-GO" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "CSC-GO",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-GO" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 5 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-GO" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 5 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-GO" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "JFA/IP/07758",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-JF" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "CSC-JF",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-JF" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 5 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-JF" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 5 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-JF" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SPO/IP/44901",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-SP" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "CSC-SP",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-SP" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 7 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-SP" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 7 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-SP" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PTS/IP/03564",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSJI" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "CSJI",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSJI" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 7 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSC-JF" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 7 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CSJI" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/1.105"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VTA/MULTI/60177",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HEC" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "HEC",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HEC" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 9 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HEC" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface Multilink1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 9 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HEC" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface Multilink1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "STA/MULTI/60117",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HMRP" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "HMRP",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HMRP" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 9 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HMRP" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface Multilink1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 9 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HMRP" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface Multilink1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TRL/IP/02977",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HSJ" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "HSJ",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HSJ" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 11 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HSJ" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 11 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HSJ" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PTS/IP/03541",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CCSCPT" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "CCSCPT",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CCSCPT" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 11 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CCSCPT" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 11 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "CCSCPT" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CCS/MULTI/60242",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HSL" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "HSL",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HSL" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 13 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HSL" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface Multilink1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 13 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HSL" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface Multilink1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PTS/IP/03540",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HST" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "HST",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HST" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 13 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HST" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 13 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HST" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0.4"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "GRS/IP/03329",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "LMR" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "LMR",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 15 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "LMR" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 15 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "LMR" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/1.9"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 15 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "LMR" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/1.9"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "STA/IP/00156",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "ESC" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "ESC",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 15 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "ESC" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 15 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "ESC" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 15 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "ESC" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface Serial0/0/0.1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SPO/IP/44897",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HAM" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "HAM",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 17 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HAM" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 17 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HAM" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 17 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HAM" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "BNU/IP/01070",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HSI" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "HSI",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 17 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HSI" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 17 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network Traffic" },
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HSI" },
     "itServiceFilter": "HAM",
     "item": { "filter": "Download LAN" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 17 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network Traffic" },
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HSI" },
     "itServiceFilter": "HAM",
     "item": { "filter": "Upload LAN" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RJO/IP/23498",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "Router MPLS-CSSJ" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "CSSJ",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 19 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "Router MPLS-CSSJ" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 19 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "Router MPLS-CSSJ" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/0.113"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 19 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "Router MPLS-CSSJ" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/0.113"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TRO/IP/00308",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HNSC" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "HNSC",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 19 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HNSC" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 19 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network Traffic" },
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HNSC" },
     "itServiceFilter": "HAM",
     "item": { "filter": "Download LAN" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 19 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network Traffic" },
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HNSC" },
     "itServiceFilter": "HAM",
     "item": { "filter": "Upload LAN" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TRS/IP/00194",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HCNSC" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "HCNSC",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 21 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HCNSC" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 21 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HCNSC" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Incoming traffic on interface GigabitEthernet0/1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 21 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "MPLS" },
     "host": { "filter": "HCNSC" },
     "itServiceFilter": "HAM",
     "item": {
      "filter": "Outgoing traffic on interface GigabitEthernet0/1"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TIJ/IP/00137",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HSJ-TIJUCAS" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disponibilidade $Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "itServiceFilter": "HSJ-T",
     "item": { "filter": "" },
     "mode": 1,
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP loss 1h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 21 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HSJ-TIJUCAS" },
     "itServiceFilter": "HAM",
     "item": { "filter": "ICMP loss" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 21 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network Traffic" },
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HSJ-TIJUCAS" },
     "itServiceFilter": "HAM",
     "item": { "filter": "Download port1" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 21 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network Traffic" },
     "group": { "filter": "FIREWALLS" },
     "host": { "filter": "FIREWALL FORTIGATE HSJ-TIJUCAS" },
     "itServiceFilter": "HAM",
     "item": { "filter": "Upload port1" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}